### ISSUE TITLE
Nested merging does not work (and should)

### ISSUE THREAD

**Issue by darscan** [snyk/config#8]
Nconf handles merging. Snyk Config breaks this here: 

https://github.com/snyk/config/blob/develop/lib/index.js#L30

Here's a test that fails (but should pass):

https://github.com/snyk/config/blob/test/nested-merge/test/index.test.js#L43

**Comment by adrukh** [comment]
Nested merging does not work for `process.env` keys, but does work for files being read. Closing for now as #11 introduces a new layer for config secrets.
